%canon_reldir%_binderincdir = $(includedir)/android/frameworks-native-$(LAARID_API_VERSION)/binder
%canon_reldir%_binderinc_HEADERS = \
    %reldir%/binder/AppOpsManager.h \
    %reldir%/binder/Binder.h \
    %reldir%/binder/BinderService.h \
    %reldir%/binder/BpBinder.h \
    %reldir%/binder/BufferedTextOutput.h \
    %reldir%/binder/Debug.h \
    %reldir%/binder/IAppOpsCallback.h \
    %reldir%/binder/IAppOpsService.h \
    %reldir%/binder/IBatteryStats.h \
    %reldir%/binder/IBinder.h \
    %reldir%/binder/IInterface.h \
    %reldir%/binder/IMediaResourceMonitor.h \
    %reldir%/binder/IMemory.h \
    %reldir%/binder/IPCThreadState.h \
    %reldir%/binder/IPermissionController.h \
    %reldir%/binder/IProcessInfoService.h \
    %reldir%/binder/IResultReceiver.h \
    %reldir%/binder/IServiceManager.h \
    %reldir%/binder/MemoryBase.h \
    %reldir%/binder/MemoryDealer.h \
    %reldir%/binder/MemoryHeapBase.h \
    %reldir%/binder/Parcelable.h \
    %reldir%/binder/Parcel.h \
    %reldir%/binder/PermissionCache.h \
    %reldir%/binder/PersistableBundle.h \
    %reldir%/binder/ProcessInfoService.h \
    %reldir%/binder/ProcessState.h \
    %reldir%/binder/Status.h \
    %reldir%/binder/TextOutput.h
